# foot.ini
# https://man.archlinux.org/man/foot.ini.5.en

shell=/usr/bin/zsh

font=Monaspace Argon:size=6

dpi-aware=yes

resize-delay-ms=250
resize-by-cells=no
resize-keep-grid=no

# initial-color-theme=dark

bold-text-in-bright=palette-based

[desktop-notifications]
command=notify-send -a ${app-id} -i ${app-id} ${title} ${body}command=notify-send -a ${app-id} -i ${app-id} ${title} ${body}command=notify-send -a ${app-id} -i ${app-id} ${title} ${body}command=notify-send -a ${app-id} -i ${app-id} ${title} ${body}

[scrollback]
lines=100000

[cursor]
style=block
unfocused-style=hollow
blink=yes
blink-rate=500

# Gruvbox Dark color scheme
[colors]
cursor= ebdbb2 fbf1c7
background= 282828
foreground= ebdbb2
regular0=   282828 # black
regular1=   cc241d # red
regular2=   98971a # green
regular3=   d79921 # yellow
regular4=   458588 # blue
regular5=   b16286 # magenta
regular6=   689d6a # cyan
regular7=   a89984 # white
bright0=    1d2021 # black
bright1=    fb4934 # red
bright2=    b8bb26 # green
bright3=    fabd2f # yellow
bright4=    83a598 # blue
bright5=    d3869b # magenta
bright6=    8ec07c # cyan
bright7=    fbf1c7 # white
